### ISSUE TITLE
Multiple theorems defined within the same \declaretheorem command?

### ISSUE THREAD

**Issue by dbitouze** [muzimuzhi/thmtools#2]
Would be nice if multiple theorems could be defined within the same `\declaretheorem` command if they share the same options? It could be helpful for instance to specify just once the options which applies to many theorems, for instance:

```latex
\declaretheorem[style=mystyle,parent=section]{theorem,corollary,axiom}
```

**Comment by muzimuzhi** [comment]
Only one concern: `\declaretheorem{theorem, corollary}` might make editors (like TeXstudio) unable to recognize environments `theorem` and `corollary`.
