### ISSUE TITLE
something went wrong when using `\declaretheoremstyle` and `\declaretheorem` in LaTeX3

### ISSUE THREAD

**Issue by xkwxdyy** [muzimuzhi/thmtools#26]
I want to remove the `.` after the head, i.e. make `headpunct = {}`, but the key `headpunct` is only available in `\declaretheoremstyle`, so I used it to create a new style without `.`, but something goes wrong with it when I used it in LaTeX3, here is a  MWE:
```latex
\documentclass{ctexbook}
\usepackage{amsthm}
\usepackage{thmtools}
\ExplSyntaxOn
\declaretheoremstyle
  [
    spaceabove = 3pt,
    spacebelow = 3pt,
    headfont = \bfseries,
    bodyfont = \normalfont,
    headpunct = {},
    postheadspace = { },
    headindent = {},
    notefont = { \fontseries \mddefault \upshape }
  ]{ccnustyle}
\cs_new:Npn \__xdyymath_declare_theorem_with_counter_within:n #1
  {
    \declaretheorem
      [
        style = ccnustyle,
        name =  \clist_item:nn {#1} {1} ,
        refname = \clist_item:nn {#1} {2} ,
        within = \clist_item:nn {#1} {3} ,
      ]
      { \clist_item:nn {#1} {4} }
  }
\cs_new:Npn \__xdyymath_declare_theorem_with_counter_sibling:n #1
  {
    \declaretheorem
      [
        style = ccnustyle ,
        name =  \clist_item:nn {#1} {1} ,
        refname = \clist_item:nn {#1} {2} ,
        sibling = \clist_item:nn {#1} {3} ,
      ]
      { \clist_item:nn {#1} {4} }
  }
\clist_map_function:nN
  {
    { 定理, 定理, chapter, theorem }
  }\__xdyymath_declare_theorem_with_counter_within:n

\clist_map_function:nN
  {
    { 定义, 定义, theorem, definition }
  }\__xdyymath_declare_theorem_with_counter_sibling:n
\ExplSyntaxOff


\begin{document}
\begin{definition}[limit]
  test
\end{definition}
\end{document}
```
And the fatal message is 
```bash
Missing number, treated as zero.
<to be read again> 

Illegal unit of measure (pt inserted).
<to be read again> 
```

I don't know what's wrong with it.

**Comment by xkwxdyy** [comment]
https://tex.stackexchange.com/questions/635396/something-went-wrong-when-using-declaretheoremstyle-and-declaretheorem-in

It had been solved.

**Comment by muzimuzhi** [comment]
I've added an answer on TeX-SX.

Short answer: With `amsthm` + `thmtools`, `postheadspace` accepts a length or a space or `\newline`. Within `\ExplSyntaxOn ... `\ExplySyntaxOff`, one should use `postheadspace={~}` to pass a space.

**Comment by xkwxdyy** [comment]
> I've added an answer on TeX-SX.
> 
> Short answer: With `amsthm` + `thmtools`, `postheadspace` accepts a length or a space or `\newline`. Within `\ExplSyntaxOn ... `\ExplySyntaxOff`, one should use `postheadspace={~}` to pass a space.

Thanks so much. I got it.
