### ISSUE TITLE
thmbox key causes "Proof" to be repeated in proof environment

### ISSUE THREAD

**Issue by mbertucci47** [muzimuzhi/thmtools#32]
Loading `thmbox` via the option to `\declaretheorem` causes "Proof" to be repeated in a proof environment. For example,
```latex
\documentclass{article}
\usepackage{amsthm,thmtools}
\declaretheorem[thmbox]{theorem}

\begin{document}

\begin{proof}
some text
\end{proof}

\end{document}
```
produces
<img width="200" alt="Screenshot 2023-01-30 123639" src="https://user-images.githubusercontent.com/61854785/215577972-2eaa330b-821d-457d-a8c7-e462dedd3311.png">

**Comment by muzimuzhi** [comment]
Please check if the patch below works. `thmtools` forgot to undo `thmbox`'s change to `\\proof`.
```tex
\documentclass{article}
\usepackage{amsthm,thmtools}

\usepackage{thmdef-thmbox}
\usepackage{xpatch}

\makeatletter
% patch key `thmbox` family `thmdef` defined in thmdef-thmbox.sty
\xpatchcmd\KV@thmdef@thmbox
  {\RequirePackage[nothm]{thmbox}}
  {% undo thmbox's modification to \\proof (undo \\example also?)
    \csletcs{old\@backslashchar proof}{\@backslashchar proof}%
    \RequirePackage[nothm]{thmbox}%
    \csletcs{\@backslashchar proof}{old\@backslashchar proof}%
  }
  {}{\PatchFailed}
\makeatother

\declaretheorem[thmbox]{theorem}

\begin{document}
\begin{proof}
  some text
\end{proof}
\end{document}
```
<img width="112" alt="image" src="https://user-images.githubusercontent.com/6376638/215747064-170ff158-1029-41af-bd6f-c47f693fee9f.png">

**Comment by mbertucci47** [comment]
Indeed, fixes the issue. Thanks for the fast reponse!
