### ISSUE TITLE
Make `numbered=unless unique` aware of the scope of `numberwithin`

### ISSUE THREAD

**Issue by dbitouze** [muzimuzhi/thmtools#4]
If it is possible to make compatible `numbered=unless unique` and `numberwithin` options (see #3), it could be nice to make `numbered=unless unique` aware of the scope of `numberwithin`. More explicitly: in the following MCE where "Couple" theorems are "numbered within sections" and "numbered unless unique", one could expect "Couple 2.1." and "Couple 3.1." to just be "Couple 2." and "Couple 3.".
```latex
\documentclass{article}
\usepackage{amsthm}
\usepackage{thmtools}
\usepackage[unq]{unique}
%
\declaretheorem[numberwithin=section,numbered=unless unique]{couple}
%
\begin{document}
\section{One}
\begin{couple}
  Marc \& Anne
\end{couple}
\begin{couple}
  Buck \& Britta
\end{couple}
\section{Two}
\begin{couple}
  Marc \& Anne
\end{couple}
\section{Three}
\begin{couple}
  Buck \& Britta
\end{couple}
\section{Four}
\begin{couple}
  Marc \& Anne
\end{couple}
\begin{couple}
  Buck \& Britta
\end{couple}
\end{document}
```

**Comment by muzimuzhi** [comment]
This is more complex, hence I need more time to think, read current implementation and modify.

Currently the decision whether `couple` is unique (hence un-numbered) or not is made when `couple` environment is defined. To make `unless unique` aware of `numberwithin`, that decision should be put off in every usage of `couple` env.

**Comment by muzimuzhi** [comment]
Similar code: https://wenda.latexstudio.net/q-1637.html (in Chinese).

In that question, the OP wanted to number `lemma` env only when there are multiple `lemma` usages following one `theorem`. And the numbering style of `lemma` can be independent of its `numberwithin` setting. Hence that requirement is a bit more general than what is called for in this issue.

**Comment by muzimuzhi** [comment]
@dbitouze 
All three issues are implemented. The latest code is on [`develop`](https://github.com/muzimuzhi/thmtools/tree/develop) branch. Welcome to test.

There might be problems around `\thmt@dummyctrautorefname`, which is used by `thm-restate.sty`.
