### ISSUE TITLE
really before head hook (margin notes enhancement)

### ISSUE THREAD

**Issue by GMS103** [muzimuzhi/thmtools#60]
In order to be able to put ```\todo``` (from ```todonotes```) at the same level as the head of a theorem, it seems to me that ```preheadhook``` cannot be used.

So I am doing the following hack (modifying ```amsthm.sty```):
```
\dth@everypar={%
  \@minipagefalse \global\@newlistfalse
  \@noparitemfalse
  \if@inlabel
    \global\@inlabelfalse
    \begingroup \setbox\z@\lastbox
     \ifvoid\z@ \kern-\itemindent \fi
    \endgroup
    \myheadbefore % <--- addition
    \unhbox\@labels
  \fi
  \if@nobreak \@nobreakfalse \clubpenalty\@M
  \else \clubpenalty\@clubpenalty \everypar{}%
  \fi
}%
```
which allows me to do for instance
```
\def\myheadbefore{\todo{Important}}
```
(of course the definition has to be changed before every theorem environment, but that is another question).

I was wondering if you could integrate this idea in your package.

**Comment by muzimuzhi** [comment]
Could you provide a complete latex example showing what you'd like to get?

**Comment by mbertucci47** [comment]
You can use the posthead hook and locally force `\reversemarginpar` to make the todonote appear on the left.

```tex
\documentclass{article}
\usepackage{amsthm,thmtools,todonotes}

\declaretheorem{theorem}

\addtotheorempostheadhook[theorem]{\reversemarginpar\todo{Important}}

\begin{document}

\begin{theorem}
Some text
\end{theorem}

\end{document}
```

**Comment by GMS103** [comment]
Here is an example.
```
% !TEX program = pdflatexmk
\documentclass{article}
\usepackage{todonotes} 
\reversemarginpar

\usepackage{amsthm,thmtools}
\makeatletter
\dth@everypar={
  \@minipagefalse \global\@newlistfalse
  \@noparitemfalse
  \if@inlabel
    \global\@inlabelfalse
    \begingroup \setbox\z@\lastbox
     \ifvoid\z@ \kern-\itemindent \fi
    \endgroup
    \myheadbefore 
    \unhbox\@labels
  \fi
  \if@nobreak \@nobreakfalse \clubpenalty\@M
  \else \clubpenalty\@clubpenalty \everypar{}
  \fi
}
\makeatother
\declaretheorem{theorem}

\begin{document}

Blah blah blah.

\def\myheadbefore{\todo[noline]{Important}}

\begin{theorem}[Euclid]
  For every prime $p$, there is a prime $p'>p$.
\end{theorem}

Blah blah blah.

\def\myheadbefore{}

\begin{theorem}[Euclid]
  For every prime $p$, there is a prime $p'>p$.
\end{theorem}

Blah blah blah.

\def\myheadbefore{\todo[noline,backgroundcolor=green]{Useful}}

\begin{theorem}[Euclid]
  For every prime $p$, there is a prime $p'>p$.
\end{theorem}

\end{document}
```
[thmtools_todonotes.pdf](https://github.com/muzimuzhi/thmtools/files/13787464/thmtools_todonotes.pdf)

**Comment by GMS103** [comment]
@mbertucci47:
I had already tried something like that.  But I cannot get it to work when ```postheadspace=\newline```:
```
% !TEX program = pdflatexmk
\documentclass{article}
\usepackage{todonotes} 
\reversemarginpar

\usepackage{amsthm,thmtools}
\declaretheoremstyle[
    postheadspace=\newline,
    postheadhook={\myheadbefore},
    ]
    {mytheostyle}
\declaretheorem[style=mytheostyle]{theorem}

\begin{document}

Blah blah blah.

\def\myheadbefore{\todo[noline]{Important}}

\begin{theorem}[Euclid]
  For every prime $p$, there is a prime $p'>p$.
\end{theorem}

Blah blah blah.

\def\myheadbefore{}

\begin{theorem}[Euclid]
  For every prime $p$, there is a prime $p'>p$.
\end{theorem}

Blah blah blah.

\def\myheadbefore{\todo[noline,backgroundcolor=green]{Useful}}

\begin{theorem}[Euclid]
  For every prime $p$, there is a prime $p'>p$.
\end{theorem}

\end{document}
```

**Comment by mbertucci47** [comment]
@GMS103 Yes that is more difficult. If you know the theorem will always add a new line, you can manually adjust your `\todo` like in this [TeX.sx post](https://tex.stackexchange.com/a/639371/208544).

**Comment by GMS103** [comment]
I also tried that (with ```-\baselineskip```), but the height of the line after the head is unknown beforehand.

In any case, I was asking for a general mechanism to get something "really before the head".

**Comment by muzimuzhi** [comment]
Try `preheadhook={\AddToHookNext{para/begin}{\myheadbefore}}`, which makes use of LaTeX paragraph hooks introduced in LaTeX 2021-06-01 and documented in `texdoc ltpara-doc`.

```tex
\documentclass{article}
\usepackage{todonotes}
\reversemarginpar

\usepackage{amsthm,thmtools}

\declaretheoremstyle[
    postheadspace=\newline,
    preheadhook={\AddToHookNext{para/begin}{\myheadbefore}},
  ]{mytheostyle}
\declaretheorem[style=mytheostyle]{theorem}

\begin{document}

Blah blah blah.

\def\myheadbefore{\todo[noline]{Important}}

\begin{theorem}[Euclid]
  For every prime $p$, there is a prime $p'>p$.
\end{theorem}

Blah blah blah.

\def\myheadbefore{}

\begin{theorem}[Euclid]
  For every prime $p$, there is a prime $p'>p$.
\end{theorem}

Blah blah blah.

\def\myheadbefore{\todo[noline,backgroundcolor=green]{Useful}}

\begin{theorem}[Euclid]
  For every prime $p$, there is a prime $p'>p$.
\end{theorem}

\end{document}
```

![image](https://github.com/muzimuzhi/thmtools/assets/6376638/72cde6eb-0eab-468b-a829-3dbc02212913)

BTW I'm going to edit https://github.com/muzimuzhi/thmtools/issues/60#issuecomment-1871252419 to add two missing `%` in `\dth@everypar={...}`. They were there in original snippet in https://github.com/muzimuzhi/thmtools/issues/60#issue-2058426613, but somehow got lost in following full example and caused paragraph indent.

**Comment by mbertucci47** [comment]
@muzimuzhi I think the lack of lines is expected from the `noline` option passed to `\todo`. Also, good idea using the par hooks!

**Comment by GMS103** [comment]
@muzimuzhi
Sorry for my late answer, using ```preheadhook``` works.
Thanks.
