### ISSUE TITLE
(Discussion) new package keytheorems

### ISSUE THREAD

**Issue by mbertucci47** [muzimuzhi/thmtools#69]
I've written a package [keytheorems](https://github.com/mbertucci47/keytheorems) that builds on much of the thmtools code, at some points blatantly plagiarizes it (see, for example, the code for `\listofkeytheorems`), and even allows for identical syntax with the `thmtools-compat` option. As far as I can tell all of this is allowed under the LPPL, however I wanted to make sure the maintainer of thmtools had a chance to voice any concerns or suggestions before I upload the package to CTAN. If you have none, please feel free to close this issue.

For context, I wrote the package as an exercise in using expl3, but over time I've added most of the functionality of thmtools and in the process fixed a few nagging thmtools bugs. See the keytheorems [README](https://github.com/mbertucci47/keytheorems?tab=readme-ov-file#thmtools-issues-resolved-by-keytheorems) for a list of open issues fixed by keytheorems. There are also sections titled [Differences with thmtools](https://github.com/mbertucci47/keytheorems?tab=readme-ov-file#differences-with-thmtools) and [Notes/issues on thmtools, not on Github](https://github.com/mbertucci47/keytheorems?tab=readme-ov-file#notesissues-on-thmtools-not-on-github).

**Comment by muzimuzhi** [comment]
Well I have to say, I'm not a competent maintainer of `thmtools`. Very happy you create a new theorem package which can be used as a replacement of `thmtools`.
